/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kataPrimeFactorsStarterJava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PrimeFactorsTests {
    @Test void testSomeLibraryMethod() {
        PrimeFactors pf = new PrimeFactors();
        assertTrue(pf.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
