/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kataPrimeFactorsStarterJava;

public class PrimeFactors {
    public boolean someLibraryMethod() {
        return true;
    }
}
